services:
  unreal:
    image: "tensorworks/buccaneerdemo-application"
    command: [ "-PixelStreamingURL=ws://127.0.0.1:8888", "-BuccaneerURL=http://127.0.0.1:8000" ]
    container_name: unreal
    network_mode: "host"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]
            count: 1

  cirrus:
    image: "tensorworks/buccaneerdemo-cirrus"
    container_name: cirrus
    network_mode: "host"

  buccaneerserver:
    image: "tensorworks/buccaneerdemo-buccaneerserver"
    container_name: buccaneerserver
    network_mode: "host"

  prometheus:
    image: "prom/prometheus"
    container_name: prometheus
    network_mode: "host"
    volumes:
    - "../../Configs/prometheus.yml:/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana
    container_name: grafana
    network_mode: "host"
    volumes:
    - "../../Configs/grafana-dashboard-config.yaml:/etc/grafana/provisioning/dashboards/grafana-dashboard-config.yaml"
    - "../../Configs/grafana-datasource-config.yaml:/etc/grafana/provisioning/datasources/grafana-datasource-config.yaml"
    - "../../Dashboards/:/etc/dashboards"

  loki:
    image: grafana/loki
    container_name: loki
    network_mode: "host"
    volumes:
    - "../../Configs/loki-local-config.yaml:/etc/loki/loki-local-config.yaml"

  promtail:
    image: grafana/promtail
    container_name: promtail
    command: -config.file=/etc/promtail/promtail-local-config.yaml
    network_mode: "host"
    volumes:
    - "../../Configs/promtail-local-config.yaml:/etc/promtail/promtail-local-config.yaml"
    - "eventslogs:/EventsServer"

volumes:
  eventslogs:
