# my global config
global:
  scrape_interval: 2s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 2s # Evaluate rules every 15 seconds. The default is every 1 minute.

scrape_configs:
  - job_name: "realtime_stats"
    static_configs:
      - targets: ["127.0.0.1:8000"]
